### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by SynapseScribe** [dic1911/android_URLSanitizer#1]
FATAL EXCEPTION: main
Process: moe.dic1911.urlsanitizer, PID: 28247
java.lang.RuntimeException: Unable to start activity ComponentInfo{moe.dic1911.urlsanitizer/moe.dic1911.urlsanitizer.MainActivity}: android.view.InflateException: Binary XML file line #10 in moe.dic1911.urlsanitizer:layout/activity_main: Binary XML file line #8 in moe.dic1911.urlsanitizer:layout/content_main: Error inflating class androidx.fragment.app.FragmentContainerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3388)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3527)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.view.InflateException: Binary XML file line #10 in moe.dic1911.urlsanitizer:layout/activity_main: Binary XML file line #8 in moe.dic1911.urlsanitizer:layout/content_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #8 in moe.dic1911.urlsanitizer:layout/content_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: androidx.fragment.app.Fragment$c: Unable to instantiate fragment androidx.navigation.fragment.NavHostFragment: make sure class name exists
	at a.k.d.m.d(Unknown Source:29)
	at androidx.fragment.app.Fragment.x(Unknown Source:8)
	at a.k.d.q$c.a(:2)
	at androidx.fragment.app.FragmentContainerView.<init>(Unknown Source:78)
	at a.k.d.o.onCreateView(Unknown Source:16)
	at a.k.d.e.onCreateView(:4)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)
	at EdHooker_.hook(Unknown Source:165)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at EdHooker_.hook(Unknown Source:156)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at a.b.k.h.l(Unknown Source:23)
	at a.b.k.e.setContentView(Unknown Source:4)
	at moe.dic1911.urlsanitizer.MainActivity.onCreate(Unknown Source:118)
	at android.app.Activity.performCreate(Activity.java:7820)
	at android.app.Activity.performCreate(Activity.java:7809)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3363)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3527)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)

Android runtime
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ClassNotFoundException: androidx.navigation.fragment.NavHostFragment
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at a.k.d.m.c(:2)
	at a.k.d.m.d(Unknown Source:2)
	... 36 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.navigation.fragment.NavHostFragment" on path: DexPathList[[zip file "/data/app/moe.dic1911.urlsanitizer-tsEsLCFwnxQY3jlA4K5l2g==/base.apk"],nativeLibraryDirectories=[/data/app/moe.dic1911.urlsanitizer-tsEsLCFwnxQY3jlA4K5l2g==/lib/arm64, /system/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 40 more

**Comment by SynapseScribe** [comment]
Android q, latest magisk , edxposed

**Comment by UltraBlackLinux** [comment]
Same here: android q, magisk

**Comment by dic1911** [comment]
I think it's due to a ProGuard rule is missing, should be fixed with the upcoming update.

**Comment by SynapseScribe** [comment]
Not crashing anymore on 1.1.1.3
